add a `current_standby()` method when the pin implements `StatefulOututPin`, and fix clippy+tests
rust-embedded-community/tb6612fng-rs pull request #26
Opened 2023-12-09 16:23 UTC by ripytide

Let me know if there is a better name than `current_standby`

2023-12-11 11:03 UTC, rursprung requested changes
see previous comment

2023-12-11 11:46 UTC, ripytide commented
I've updated the commits to reflect on the changes to `master`.

This is more about consistency, the `Motor` has a `current_drive_command()` method yet their is no similar method for the `current_standby()`.

2023-12-19 09:38 UTC, rursprung commented
sorry for not having replied yet. i'm still contemplating whether it actually makes sense to have these methods (both `current_standby` as suggested by you as well as `current_drive_command`) - based on my previous argument the consumer should know the state, right? i added it here because i had the need to know the state when i built it and just decided on putting it in here rather than keeping it in the consumer.

what was the reason why you contributed this method? do you have a use-case which is being simplified by having this method?

2023-12-19 14:32 UTC, rursprung commented
> In fact, I now use the second method and no longer need this pull request. Perhaps you could also remove the `current_drive_command()` method which would also restore consistency.

i certainly want to have it consistent, i'm just unsure which option is better. but i guess it's not a big deal to have this method to make it easier for consumers.

i just realised an inconsistency: when i create the `Motor` i implicitly assume that the current state is that it's stopped, but i don't issue this as an actual command, so `current_drive_command` might differ from this depending on what was previously done with the pins. i think i should explicitly stop the motors on `new` (and possibly add a second `new_with_drive_command` so that it can be initialised with another setting if it shouldn't start in a safe state but e.g. continue from something else - though i think that can be added when somebody has that use-case), then it'd be guaranteed to match.
i found this when thinking about `current_standby`: initially we might not know the state if it has never been set. should `Tb6612fng::new` set the standby pin (and if so: enable or disable it?)? how does `StatefulOutputPin::is_set_high` respond if it hasn't been set so far? since the e-h docs don't mention it i presume that this might be implementation-specific?

2024-01-09 22:48 UTC, rursprung commented
@ripytide: it'd be great to get your feedback on my previous comment!
i also saw that you pushed an update for e-h 1.0 RC.3 to this branch. 1.0 (no RC!) has just been released, so we can soon update to that, once there are matching releases from both `embedded-hal-mock` (open PR: https://github.com/dbrgn/embedded-hal-mock/pull/105) and `stm32f4xx-hal` (open PR: https://github.com/stm32-rs/stm32f4xx-hal/pull/723; needed for the example). i'd also prefer doing that update in a separate PR to keep the discussions separate, i hope that's ok for you?

2024-01-09 22:58 UTC, ripytide commented
I didn't mean to add the version commit to this PR I was using my GitHub fork as a cargo git dependency while debugging some embedded_hal version issues.

As for your previous comment, I think it's more flexible for the library consumers to keep the internal state, including for standby, since even if they don't use it it doesn't hurt to have the functionality available. I would also agree that `new` should probably set outputs to some sane and documented defaults.

2024-01-09 23:02 UTC, rursprung commented
great! then i'd propose to do the following in three separate PRs:
* update to e-h 1.0 (once the prerequisites have been merged & released)
* update `new` to set sensible defaults
* add `current_standby` (i only feel comfortable doing this _after_ `new` has been modified to ensure that we return something sensible)

feel free to contribute any of the other two PRs besides this one! otherwise i'll try to get around to them at some point (though i'm a bit busy right now with other things, might take a week or so)

do you know the answer to this one?


> how does `StatefulOutputPin::is_set_high` respond if it hasn't been set so far? since the e-h docs don't mention it i presume that this might be implementation-specific?

2024-01-09 23:48 UTC, ripytide commented
I'll have a go at the Par's tomorrow.

`StatefulOutputPin::is_set_high()`  in my use use of the `esp32_hal` the implementation reads the gpio registers to see if it is set high or low rather than keeping the state in an "rust" variable, though other implementations might do that.

2024-01-13 18:44 UTC, ripytide commented
@rursprung This PR and #35 should now be ready for review.

2024-01-15 10:41 UTC, rursprung submitted a review, later dismissed

2024-01-15 10:41 UTC, rursprung commented on CHANGELOG.md
> +standby mode.
indentation needs to be fixed so that it's correctly rendered
```suggestion
   standby mode.
```

on the other hand you can also just put everything on one line - i think the days where people could only see 72 characters per line are mostly over 🙂 (one exception where i still expect it: git commit messages)

2024-01-15 10:41 UTC, rursprung commented on src/lib.rs
> +        self.standby.is_set_high().unwrap()
you're now also using `unwrap` here which you criticized in #34 - i'm fine with merging this PR first and then addressing it afterwards as part of the other issue.
alternatively you could directly change the API of the new method to return a `Result` so that it doesn't change soon after being introduced? though in that case it might make sense to implement #34 first so that we don't have one API with error propagation and the others without?

2024-01-15 12:05 UTC, ripytide commented on src/lib.rs
> +        self.standby.is_set_high().unwrap()
while doing #34 I found the `brake()` `drive_forward()` `drive_backward()` functions all kind of redundant given you can just use the `drive()` function is this also the right sort of time to suggest removing them as well?

2024-01-15 12:12 UTC, rursprung commented on src/lib.rs
> +        self.standby.is_set_high().unwrap()
> while doing #34 I found the `brake()` `drive_forward()` `drive_backward()` functions all kind of redundant given you can just use the `drive()` function is this also the right sort of time to suggest removing them as well?

to be honest i added them as convenience functions as `motor.drive_forward(speed)` i considered it more readable than `motor.drive(DriveCommand::Forward(speed))`. it does increase the API surface of the lib, but not the the point where i consider it unmaintainable.
if you have a strong feeling that these functions should be removed i'd suggest you raise a separate ticket where we can discuss this (as i fear that it'll get lost when we do it in this comment thread here on an unrelated PR)

PS: i've sent you an email (to the address you use on the commits)

2024-02-07 15:05 UTC, rursprung commented
in general, this looks good to me. as agreed, we'll first get #37 in and then merge this. when you rebase this (and adapt it to propagate the error) please also squash the commits

2024-03-08 17:48 UTC, ripytide commented
@rursprung I've rebased and squashed this PR now that #37 is merged so this should be ready for review

2024-03-08 22:32 UTC, rursprung approved these changes

2024-03-08 22:32 UTC, merged

2024-03-08 22:33 UTC, rursprung commented
thanks @ripytide!