Add error propagation from the `embedded_hal` functions
rust-embedded-community/tb6612fng-rs pull request #37
Opened 2024-01-15 12:51 UTC by ripytide

Also I though it might be nice to reduce the API surface by removing the `drive_forward`, `drive_backward`, `stop` and `brake` functions which make the library harder to maintain and also adds confusing redundancy as it leaves two ways of accomplishing the same thing, `drive()` vs the other commands.

2024-01-15 13:26 UTC, rursprung requested changes
thank you for your contribution!

some requests from my side (besides the comments in the code):
* please split this into atomic commits (and possibly atomic PRs; i'm still a bit on the fence about the last point)
** one for the error propagation
** one for `Backwards` => `Backward` (thanks for catching that!)
** one for removing the APIs
* please use [proper commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) (also mentioned [in the Git Book](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project))

2024-01-15 13:26 UTC, rursprung commented on src/lib.rs
> +    /// An error in setting the output of the IN1 pin
```suggestion
    /// An error in setting the output of the IN2 pin
```

2024-01-15 13:26 UTC, rursprung commented on src/lib.rs
> +    In1Error(IN1Error),
is there an actual need to have it this fine-grained? why not just `Other(Error)` similar to what e-h is doing (see e.g. [`embedded_hal::digital::ErrorKind::Other`](https://docs.rs/embedded-hal/latest/embedded_hal/digital/enum.ErrorKind.html#variant.Other).

realistically we can only have two kinds of errors from the HAL: one for the `OutputPin` and one for the `DutyCycle` (aka PWM). so there shouldn't be a need to have one per pin.

maintainability seems to be worse with having all these different types as you now have quite a bit of generics-hell.

2024-01-15 13:26 UTC, rursprung commented on src/lib.rs
> +pub enum InitError<
see my comment above. i'm not sure whether this is particularly helpful to any consumer compared to a simple `Other`?

instead of having `DriveError` & `InitError` we could also have a more generic `Error` (again, with a simple `Error::Other`). then you also don't need a `.map_err` call

2024-01-15 13:47 UTC, ripytide commented on src/lib.rs
> +    In1Error(IN1Error),
Theoretically, a `hal` implementation could have different types for different pins, perhaps due to different hardware properties for different pins such as `FastPin` or a `SlowPin` or something. This way we don't enforce the consumer to use the same types. Another example might be if a consumer wraps a pin in their own type to add functionality which then wouldn't play nicely.

2024-01-15 13:51 UTC, ripytide commented on src/lib.rs
> +pub enum InitError<
And similar to my comment above there may be scenarios where they need to handle the different types of errors differently and as library authors we should try to make the functionality as flexible as possible so the library can be used for every use-case.

2024-01-15 14:01 UTC, ripytide commented
While in future I will try to note your preference for atomic commits (apologies I forgot since last time you asked), I think it would be not worth the effort for me to split this into multiple commits as I'd have to re-do everything from scratch again.

I don't think its generally a great idea to expect open-source contributors (particularly new contributors) to stick to such a commit-schema as it may discourage committers without enough know-how of `git` from making pull requests.

2024-01-17 16:15 UTC, rursprung commented on src/lib.rs
> +pub enum InitError<
how about
```suggestion
pub enum Tb6612fngError<
```
?

and renaming `DriveError` to `MotorError`? then we have one error-enum per struct. this _might_ make things clearer?

2024-01-17 16:19 UTC, rursprung commented
> While in future I will try to note your preference for atomic commits (apologies I forgot since last time you asked), I think it would be not worth the effort for me to split this into multiple commits as I'd have to re-do everything from scratch again.
> 
> I don't think its generally a great idea to expect open-source contributors (particularly new contributors) to stick to such a commit-schema as it may discourage committers without enough know-how of `git` from making pull requests.

i think it's important to (try to) uphold the standards also (and especially) in open source projects, both to make them maintainable & understandable in the long-term but also to teach people the best practices.

for this specific PR i think it's fine if you squash the commits together and provide a nice commit message (you can go with a generic "refactor: streamline API and expose errors through `Result`" and then add a nice description to it - this way you can always claim that it's atomic enough 😉)

i think i'm ok with removing the duplicate methods. for the `Result` thing i'll briefly ping the [rust embedded matrix room](https://matrix.to/#/#rust-embedded:matrix.org) to see what the general consensus/recommendation on this is (seeing that the `Result` thing is a very new thing on the pins).

2024-01-17 17:04 UTC, ripytide commented on src/lib.rs
> +pub enum InitError<
I think that's a good idea, consistency like this is always nice.

2024-02-29 05:55 UTC, rursprung commented
@ripytide: sorry for the long delay here! https://github.com/rust-embedded/embedded-hal/issues/576 has been discussed in the last rust-embedded meeting ([see the meeting minutes](https://hackmd.io/-u0QJ3xDQxunspS_XOrwfw)) and the approach chosen here is considered best practices for `no_std` (with `std` there are cleaner/easier options).

could you please:
* rebase the PR
* squash everything into one commit with a nice commit message (see previous comment)
?

with that i can then ACK & merge it and we can get your other PR in as well and finally release this thing!

2024-03-03 11:16 UTC, ripytide commented
@rursprung I have rebased and squashed the PR

2024-03-06 07:01 UTC, rursprung approved these changes
thanks a lot for this!

2024-03-06 07:02 UTC, merged